---
- name: Printing examples
  hosts: all
  gather_facts: false

  tasks:
    - name: Print custom credential
      ansible.builtin.debug:
        msg: "This is my vcenter username: {{ MY_VCENTER_USERNAME }}"
