---
- name: Reboot host based on operating system
  hosts: all
  gather_facts: true

  tasks:
    - name: Reboot Linux host
      ansible.builtin.reboot:
        msg: "Rebooting Linux host {{ inventory_hostname }}"
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      become: true
      when: ansible_system == "Linux"

    - name: Reboot Windows host
      ansible.windows.win_reboot:
        msg: "Rebooting Windows host {{ inventory_hostname }}"
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      become: true
      when: ansible_system == "Win32NT"
